### ISSUE TITLE
use same OTP multiple times in the same period?

### ISSUE THREAD

**Issue by dsnytech-egplusww** [Spomky-Labs/otphp#113]
| Q                    | A
| -------------------- | -----
| Bug report?          | no
| Feature request?     | no
| BC Break report?     | no
| RFC? / Specification | no
| Library version      | 9.1

This is a question, not an issue.

Will this library allow a user to use an OTP more than once in the period of 30 seconds?

I would like to prevent reusing an OTP more than once in a period.
Is this a configurable option?

**Comment by Spomky** [comment]
A code is valid within the period.
It is possible to prevent reusing this code, but this is completely out of scope of the specification.
This should be managed on your application side as well as bruteforce mitigation (kind of blacklist limited to the current period).

**Comment by dsnytech-egplusww** [comment]
Thank you @Spomky

**Comment by sa-linetco** [comment]
@Spomky hi there! we added a feature to only accept codes after the period of a given timestamp.

would you be interested in a pull request? i would only need to add unit tests and make sure to comply with your contributing.md :)

you can have a look at it in our fork at: https://github.com/Spomky-Labs/otphp/compare/v10.0...dh-linetco:add-option-to-only-accept-otp-codes-after-a-given-timestamp
