### ISSUE TITLE
Period not working long enough

### ISSUE THREAD

**Issue by jasonfish568** [Spomky-Labs/otphp#121]
| Q                    | A
| -------------------- | -----
| Bug report?          | yes
| Feature request?     | no
| BC Break report?     | no
| RFC? / Specification | no
| Library version      | 9.1

```
$otp = \OTPHP\TOTP::create(
            $encoded, // Let the secret be defined by the class
            60,     // The period (60 seconds)
            'sha1', // The digest algorithm
            10      // The output will generate 10 digits
        );
        $result=$otp->verify($code,time());
```

I have faced a problem that the period an otp works is usually no more than 20 seconds when I actually set the period to 60.

I have checked the system timestamp, the time when an otp is generated and the time when the otp is verified has just a bit more than 20 seconds.

When generating the otp, I created an TOTP instance at that time. The user send thru the otp to another route after waiting around 20 seconds, this verify route has another function so I have another TOTP instance created after 20 seconds. Now, it doesn't verify the otp. 

I have also checked the source code but just can't figure out what is going wrong.

**Comment by jasonfish568** [comment]
This can be duplicated using PHPUnit. Simply use sleep() to wait.
When setting period to 120, sleep(60) then verify will return false;

**Comment by jasonfish568** [comment]
I also have read this comment https://github.com/Spomky-Labs/otphp/issues/68#issuecomment-292502017 but getting confused.

What I am thinking is, if I created an otp at timestamp 123456789 and set period = 60. Then at any timestamp before 123456849, the verify should return true. This cannot be done by window and TBH I don't understand how window works for TOTP. If TOTP has set a period, then window for TOTP is simply letting the otp be valid for much longer than it should be.

**Comment by Spomky** [comment]
Let say the period is 1000 (it will be easier to understand).
An OTP will be valid from 123456000 to 123456999.

If you ask for the OTP at 123456789, the OTP is already valid for 789 seconds and will change after 210 seconds.

This is exactly what append with your example, except that the period is different.

> This can be duplicated using PHPUnit. Simply use sleep() to wait.
When setting period to 120, sleep(60) then verify will return false;

This is not the way you should test the OTP lifecycle.

* You first have to know the timecode: `$timecode = (int) floor(time()/$period)`.
* You can then know when the OTP starts to live: `$startTime = $timecode*$period`
* And know when the OTP will change: `$nextOtpAt = ($timecode+1)*$period`
* For a given timestamp, you can then know the remaining seconds before change: `$remainingTime = $nextOtpAt - time()`

If you want to check if the OTP really lives 60 seconds, you should do:

```php
<?php

declare(strict_types=1);

use OTPHP\TOTP;

$otp = TOTP::create(null, 60);

$timecode = (int) floor(time()/$otp->getPeriod());
$startTime = $timecode*$otp->getPeriod();
$nextOtpAt = ($timecode+1)*$otp->getPeriod();

//Check OTP from previous period
dump($otp->at($startTime-1));

//period*identical values
for($at = $startTime; $at <$nextOtpAt; $at++) {
    dump($otp->at($at));
}

//Check OTP from next period
dump($otp->at($at+1));
```

I close for now as there is no bug here.
Feel free to continue the discussion if needed.

**Comment by jasonfish568** [comment]
Thanks for your explanation Spomky. I now understand the way how the lifecycle works. It doesn't start from the time it gets created. But let's say at any timestamp I create an otp, I would like to make it alive for exactly 60 seconds since that timestamp. How can I archive this?

@Spomky

**Comment by Spomky** [comment]
>  It doesn't start from the time it gets created.

That's it!

>  would like to make it alive for exactly 60 seconds since that timestamp. How can I archive this?

This is not a use case defined by the specification.
There could be a (very tricky) way to do that knowing the current time, the start of the period and using the epoch feature (time drift for timecode computation).

Example (not tested):

```php
<?php

$period = 60;
$timecode = (int) floor(time()/$period);
$startTime = $timecode*$period;
$elapsedTimeSinceOtpCreation = time()-$startTime;

$otp = TOTP::create(
    null,                        // Let the secret be defined by the class
    $period,                     // The period
    'sha1',                      // The digest algorithm
    6,                           // The output will generate 6 digits
    $elapsedTimeSinceOtpCreation // The epoch feature.
);
```
