### ISSUE TITLE
TOTP clock drift

### ISSUE THREAD

**Issue by pavarnos** [Spomky-Labs/otphp#124]
| Q                    | A
| -------------------- | -----
| Bug report?          | no
| Feature request?     | yes
| BC Break report?     | no
| RFC? / Specification | no
| Library version      | latest

Physical TOTP tokens usually have no connection to the internet, so their internal clock will drift over time. We use Feitian c200 tokens, and they usually start out exact but slowly drift to about 7-8 window units over a few years. When logging in, we allow a window size of 2 to allow a little bit of drift since we last saw the token, and to allow the user a little bit of time to physically type the number into the browser.

`verifyOtpWithWindow` will return a true / false if the password is within the window, but it won't tell us if it is near the start or the end of the window.

For longer term use of tokens, it is important to record this offset after each login so that we are effectively re-syncing the token and allowing the full width of the window for their next login. We have about 1500 tokens: many teams have a supply that sits in a box waiting for new people to sign up. So we have a sync process on setup that allows a window size of 10 in case the token has drifted a long way. But we also need a way to get the current offset from `verifyOtpWithWindow` so that each time it is used for a real login we can stay in sync. Is this something you'd consider adding to your library?

**Comment by Spomky** [comment]
Hi,

Sorry for the late answer.

I investigated a lot about that issue, but I cannot find a way to properly deal with this issue on dev side.
The problem with the window parameter is that the security drastically decrease when the number of windows increases.
A better approach could be the use of the [epoch feature](https://github.com/Spomky-Labs/otphp/blob/v9.0/doc/Customize.md#epoch-totp-only) for each user device configuration.

I haven't found any significant drift of the clock with the C200 tokens I ordered. It is a very accurate device. I am now convinced that the problem come from the lithium battery cell. In the product datasheet, we can read that it is designed for a 3 to 5 years lifetime. This may be another reason for this clock drift.

**Comment by pavarnos** [comment]
Thanks. Our tokens start good, but almost all of them drift over time. According to Feitian this is expected behaviour.

I use code like this to maintain it after every use.

```php
    /**
     * @param string $password the one time password value
     * @param int    $time     a unix timestamp
     * @param int    $offset   the value of lastCounterOffset from last time we had a valid password
     * @return bool true if the $password is valid
     */
    public function validate($password, $time = null, int $offset = 0)
    {
        if ($time === null) {
            $time = time();
        }
        $counter = $this->timestampToCounter($time, $this->getTimeStep());
        foreach ($this->getPossibleWindow() as $current) {
            if ($password === parent::calculate($counter + $current + $offset)) {
                $this->lastCounterOffset = $current + $offset;
                return true;
            }
        }
        $this->lastCounterOffset = $offset;
        return false;
    }
```

which builds on rych/otp. Our window size is 2, which allows tokens to sit in a drawer for a few months and still be fine. As long as you have other code that prevents any single value being used within the window then you are safe from replay attacks.

**Comment by Spomky** [comment]
> According to Feitian this is expected behaviour.

I am really surprised by this answer… OK in general for HW devices there is no way to easily sync the internal clock. But here 7-8 window units correspond to approx 4 minutes per year (if period of 30 sec)!

Anyway your approach looks good as the window is kept as low as possible.

**Comment by exussum12** [comment]
Could possibly either return window by ref for the drift. Or add a new method to return the window ? 

With the known window you could then adjust the epoch if you store the drift ? Happy to code one of these If needed
