### ISSUE TITLE
Google Chart API has been deprecated and will shut down March 14th 2019

### ISSUE THREAD

**Issue by briedis** [Spomky-Labs/otphp#128]
RIP QR code generation.

https://developers.google.com/chart/image/
Warning: This API is deprecated and is scheduled to be turned off on March 14, 2019. Please use the actively maintained Google Charts API instead.

**Comment by briedis** [comment]
I'm personally using this library:
https://github.com/endroid/qr-code

Url, which can be used in HTML for img attribute: 

```
$url = (new \Endroid\QrCode\QrCode($string))->writeDataUri();
```

**Comment by Spomky** [comment]
Thank you. I missed that notification.
The documentation recommends the use of [a dedicated QR code generator](https://github.com/Spomky-Labs/otphp/blob/v9.0/doc/index.md#how-to-use)

I think I will depreciate the method [`getQrCodeUri`](https://github.com/Spomky-Labs/otphp/blob/v9.0/src/OTPInterface.php#L122) as it is no more relevant.

`endroid/qr-code` looks interesting. Eamples for each solution may also be added

**Comment by Spomky** [comment]
Closing as v10.0 is released.
The method `getQrCodeUri` is still available, but now there is no default values for the parameters.
