### ISSUE TITLE
README.md change to point to Wiki

### ISSUE THREAD

**Issue by alexhorner** [Spomky-Labs/otphp#130]
Just a quick little suggestion. The README has a link which points to the docs, and the docs do not mention the loading of a provisioning URI or the getSecret() function. This caused me a little confusion as I was happy to use the built in secret generator but did not know how to get the secret out of the OTP object to store in the database. As referenced in https://github.com/Spomky-Labs/otphp/issues/57 there is a Wiki page on what information to store in the database. Maybe this should be linked on the README or in the docs?

**Comment by Spomky** [comment]
You are right, the wiki page should be referenced in the README (it is already referenced in the [Q&A page](https://github.com/Spomky-Labs/otphp/blob/v9.0/doc/QA.md) by the way).
