### ISSUE TITLE
Deferred verification period

### ISSUE THREAD

**Issue by adrianrz** [Spomky-Labs/otphp#133]
| Q                    | A
| -------------------- | -----
| Bug report?          | no
| Feature request?     | no
| BC Break report?     | no
| RFC? / Specification | yes/no
| Library version      | x.y(.z)

First of all I congratulate you for this excellent library
I have implemented TOTP and it works fine on my local server, but when I test it on the production server, there is a mismatch in the OTP validation. Valid well if I enter the value given in Google Authenticator in the last 10 seconds (the period is by default) and even having changed the number in the app, it accept it as valid to the previous one until 20 seconds after having changed.
Any suggestions?
Note, the local server has php 7.2 and the production server php 7.3I

**Comment by Spomky** [comment]
Hi @adrianrz,

It looks like the clock of your server is slightly different from your device.
They are normally synchronized automatically to avoid that.

What you can do is to [use the `window` parameter](https://github.com/Spomky-Labs/otphp/blob/v9.0/doc/Window.md).

**Comment by adrianrz** [comment]
Hi Sompky,
you were right, there was a mismatch of about 30" between the time of the app and the time of the server.
Thank you very much.
Regards
Adrian

**Comment by Spomky** [comment]
I am happy to read that! 
So either you can sync the clocks or you can use the window parameter mentioned in my previous comment.

**Comment by Spomky** [comment]
Closing as answered.
Feel fre to open it again if needed.
