### ISSUE TITLE
Composer installs v8.3

### ISSUE THREAD

**Issue by yohancreemers** [Spomky-Labs/otphp#136]
When relying on `composer require spomky-labs/otphp` as suggested in the docs, I get v8.3 by default. 
I expected v9.0 as that branch is marked as default, and v8.3 is no longer maintained.

**Comment by jdreesen** [comment]
I just tried this in a fresh project (no other dependencies) and it installs `v10.0` as expected:
```
$ composer require spomky-labs/otphp
Using version ^10.0 for spomky-labs/otphp
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 4 installs, 0 updates, 0 removals
  - Installing thecodingmachine/safe (v0.1.16): Downloading (100%)
  - Installing beberlei/assert (v3.2.7): Downloading (100%)
  - Installing paragonie/constant_time_encoding (v2.3.0): Downloading (100%)
  - Installing spomky-labs/otphp (v10.0.0): Downloading (100%)
Writing lock file
Generating autoload files
```

Thus, I assume there are other dependencies in your project that prevent installing the latest version.

What's your PHP version? 
Do you have any of the other dependencies that are listed above installed? 
What's the output of `composer require spomky-labs/otphp:^9.0` or `composer require spomky-labs/otphp:^10.0`?

--- 
@Spomky maybe the default branch should be changed to `v10.0`?

**Comment by Spomky** [comment]
I've just changed the default branch to v10. Anyway I'm not sure it will solve the issue.
I agree with @jdreesen and it looks like you have a dependency in your project that prevent the newest versions to be installed.

**Comment by yohancreemers** [comment]
Sorry, my fault. Composer was running on PHP 5.6.31, and therefor falling back to otphp v8.3.
Thanks for your quick responses.
