### ISSUE TITLE
Why is there two v10 tags?

### ISSUE THREAD

**Issue by nesk** [Spomky-Labs/otphp#138]
I see you have two tags:

- [`v10.0.0`](https://github.com/Spomky-Labs/otphp/tree/v10.0.0)
- [`v10.0`](https://github.com/Spomky-Labs/otphp/tree/v10.0)

I think you might have created the `v10.0` release instead of a `v10.0.1` release.

**Comment by Spomky** [comment]
You are right this is a mistake.
I've just created a new `v10.0.1` tag to fix that.
Sorry for the incovenience.

**Comment by nesk** [comment]
Thank you, have a good day.
