### ISSUE TITLE
Generating recovery codes

### ISSUE THREAD

**Issue by ghost** [Spomky-Labs/otphp#139]
| Q                    | A
| -------------------- | -----
| Bug report?          | no
| Feature request?     | no
| BC Break report?     | no
| RFC? / Specification | no
| Library version      | 10.0(.1)

Hey folks,

I was wondering whether it was possible to generate recovery codes with this library. I'll have to admit that I can't find much info on the subject of generating recovery codes either, so maybe this is not the job of the library but rather something I have create myself.

**Comment by Spomky** [comment]
Backups codes are codes generated directly by your application.
They are not supposed to be associated with any device, protocol or whatever (they can be printed by the end user).

Usually, they are random strings. Length and quantity depend on your security policy.
This SO answer will help you : https://stackoverflow.com/questions/4356289/php-random-string-generator/31107425#31107425
This library will not be useful for that purpose

**Comment by ghost** [comment]
Thanks for the help! I'll close the issue.
