### ISSUE TITLE
Access generated digits

### ISSUE THREAD

**Issue by onebeat** [Spomky-Labs/otphp#142]
| Q                    | A
| -------------------- | -----
| Bug report?          | no
| Feature request?     | no
| BC Break report?     | no
| RFC? / Specification | no
| Library version      | 10.1

Hello, i am trying to figure out how can i create OTP key which i will send via sms so my client can verify himself.

`$totp = TOTP::create(
    null,   // Let the secret be defined by the class
    30,     // The period (30 seconds)
    'sha1', // The digest algorithm
    8       // The output will generate 8 digits 
);`

How can i get digits that create generated ?

**Comment by Spomky** [comment]
Hi,

The current OTP is given by the method `now()`.
But you dont't have to send it by SMS, email or whatever. It should be given by an application like Google Authenticator or FreeOTP.

**Comment by onebeat** [comment]
Ok thank you for your reply.
My idea is to use this as sms verification of registrion for my client so system generates 6 number pin which has expire frame of 60 sec or more then is entered to php form.
My question how can i verify and what should i put -> $otp->verify("entered pin") or ?

**Comment by Spomky** [comment]
hum... from my point of view, it doesn't seem appropriate.

An OTP is not necessarily valid during exactly X seconds when generated.
The time needed for a user to receive the SMS, open it, typing the OTP and validate it may take more time than the OTP lifetime.

When sending codes by email or SMS, it is preferable to use a random code with limited lifetime (approx 1h) instead of using TOTP.

**Comment by onebeat** [comment]
I agree with you but if i change from 30 sec to 600 sec which is 10min or more then i can use this, right ? I the future idea is to implement qrcode verification...

My question how and if can verfiy digit ?

**Comment by Spomky** [comment]
> My question how and if can verfiy digit ?

[It is explained in the doc](https://github.com/Spomky-Labs/otphp/blob/v10.0/doc/index.md#how-to-use)

```php 
$otp = TOTP::create($secret); // create TOTP object from the secret.
$otp->verify($input); // Returns true if the input is verified, otherwise false.
```
If you want to send a unique / temporary code by SMS/email, just don't use TOTP for that but pure random values.
TOTP will undoubtedly lead to security issues or bad UX.
