### ISSUE TITLE
Not identifying the service

### ISSUE THREAD

**Issue by theonelucas** [Spomky-Labs/otphp#143]
| Q                    | A
| -------------------- | -----
| Bug report?          | yes
| Feature request?     | no
| BC Break report?     | no
| RFC? / Specification | yes/no
| Library version      | latest

While parsing an URI without account or with service name not being an URL it breaks, example:
`otpauth://totp/BestService?algorithm=SHA1&digits=6&period=30&secret=HELLOWORLD`

If you run ```$otp = Factory::loadFromProvisioningUri($uri)``` and then  ```$this->otp->getIssuer()``` the latter will return `NULL`, where it should return `BestService`

            
If you want an example of an site that uses this URI format, [check this site](https://www.bitcointrade.com.br/)

**Comment by Spomky** [comment]
Hi @theonelucas,

According to the RFC3986 and 4226, the issuer should be

* in the query string: `otpauth://totp/label?issuer=ISSUER`
* as label prefix: `otpauth://totp/ISSUER:label`
* or both: `otpauth://totp/ISSUER:label?issuer=ISSUER`

The URI you provided has no issuer as query string and no label prefix. This is the reason why there is no issuer returned by the method `getIssuer()`. The label `BestService` is therefore considered as the account name without issuer.
