### ISSUE TITLE
question: what data to use for getting TOTP

### ISSUE THREAD

**Issue by vespino** [Spomky-Labs/otphp#145]
I was hoping to create my personal TOTP codes to not have to rely on services like Google Authenticator or Authy. I have setup your script and it's outputting stuff, works fine. What I was wondering is how to get from the QR code found in most logins when beginning the 2FA process to the TOTP to verify and eventually use to login.

I'm currently testing with Homebridge which shows the following QR code output:

`otpauth://totp/Homebridge%20UI%20([some code]):[user name]?secret=[some random string]&period=30&digits=6&algorithm=SHA1&issuer=Homebridge%20UI%20([some code])`

Can I insert the complete URI in to your script and output the verify TOTP or do I have to first cut it into pieces?

**Comment by Spomky** [comment]
> Can I insert the complete URI in to your script and output the verify TOTP or do I have to first cut it into pieces?

Hi,

No need to reinvent the wheel, the [`Factory` class](https://github.com/Spomky-Labs/otphp/blob/v10.0/doc/Factory.md) is designed for that purpose.

```php
<?php
use OTPHP\Factory;

$otp = Factory::loadFromProvisioningUri('otpauth://totp/Homebridge%20UI%20([some code]):[user name]?secret=[some random string]&period=30&digits=6&algorithm=SHA1&issuer=Homebridge%20UI%20([some code])');
$otp->verify('012345');
```

**Comment by vespino** [comment]
Thanks, it seems to be working now. I worked by extracting the secret manually from the link before and guess I waited too long to enter the code which then failed. I'm not doing anything else before, but using the Factory class will definitely make it easier for extracting data.
