### ISSUE TITLE
PHP 8

### ISSUE THREAD

**Issue by verschoof** [Spomky-Labs/otphp#146]
| Q                    | A
| -------------------- | -----
| Bug report?          | no
| Feature request?     | yes
| BC Break report?     | no
| RFC? / Specification | no
| Library version      | master

This packages blockes me for using https://github.com/scheb/2fa-google-authenticator because of PHP 8.
```
Problem 1
    - beberlei/assert[v3.0.0, ..., v3.2.7] require php ^7 -> your php version (8.0.2) does not satisfy that requirement.
    - spomky-labs/otphp[v9.1.0, ..., v9.1.4] require php ^7.1 -> your php version (8.0.2) does not satisfy that requirement.
    - scheb/2fa-google-authenticator v5.7.0 requires spomky-labs/otphp ^9.1|^10.0 -> satisfiable by spomky-labs/otphp[v9.1.0, ..., v9.1.4, v10.0.0, v10.0.1].
    - spomky-labs/otphp[v10.0.0, ..., v10.0.1] require beberlei/assert ^3.0 -> satisfiable by beberlei/assert[v3.0.0, ..., v3.3.0].
    - Root composer.json requires scheb/2fa-google-authenticator ^5.7 -> satisfiable by scheb/2fa-google-authenticator[v5.7.0].
```

Todo:
- [ ] Update dependency beberlei/assert to ^3.2 | ^3.3
- [ ] Update compser.json php ^7.0 || ^8.0
- [ ] Make issue in https://github.com/scheb/2fa-google-authenticator in to up this package

**Comment by Spomky** [comment]
Hi @verschoof,
This is not caused by this library. The v10 (PHP 8 compatible) is already used by [scheb/2fa-google-authenticator](https://github.com/scheb/2fa/blob/5.x/src/google-authenticator/composer.json#L16).
There is another dependency that is cuasing this issue (maybe beberlei/assert)

**Comment by verschoof** [comment]
Hi @Spomky,

Thanks for your fast reply!
My appologies, You are right.

In the compser.json:
```
"php": "^7.2|^8.0",
"beberlei/assert": "^3.0",  <- should match 3.3
```

It was my container that had not the intl extension, I did not expect it would ignore the 3.0 version (I was a bit mislead by the messages)
