### ISSUE TITLE
new feature made (getExpiration)

### ISSUE THREAD

**Issue by brasizza** [Spomky-Labs/otphp#149]
| Q                    | A
| -------------------- | -----
| Bug report?          | no
| Feature request?     | no
| BC Break report?     | no
| RFC? / Specification | no
| Library version      |  latest

Hello!
I like this package for OTP and it was working just fine!
I made a new feature to show how many seconds left to expire the OTP password.
I have an app that the client can close the page and open again, and because of that my counter started again in my started period. So i decided to do a method that i can calculate de expiration and i can start my timer right in the time left.

I don't know hot to put this new thing in this project. can i do a PR ?

My code will do someting like this:

$otp = TOTP::create(null,30,'sha1',6);
**echo "My token in {$otp->now()} with {$otp->getPeriod()} seconds to live and will expire in  {$otp->getExpiration()} seconds!";**

**Comment by Spomky** [comment]
Hi,

That feature seems quite trivial. It is just `$otp->now()%$otp->getPeriod()`.
This is usually done on frontend using JS/CSS for a dynamic view.
With that being said, I don't see any issue for implementating such method.
This will be done in coming minor version.

Regards.

**Comment by brasizza** [comment]
Can i send a pr for you? because i did that and than you can check if it's eligible to put in your code

**Comment by Spomky** [comment]
A PR is already created. See #151
I can get valid results using the code below:

```php
<?php

declare(strict_types=1);

require_once 'vendor/autoload.php';

$totp = \OTPHP\TOTP::create();

while(true) {
    var_dump($totp->getRemainder());
    sleep(1);
}
```

**Comment by Spomky** [comment]
Closing as this feature will be part of `v11`
