### ISSUE TITLE
OTP verification failed if set custom period

### ISSUE THREAD

**Issue by ankitchauhan22** [Spomky-Labs/otphp#153]
| Q                    | A
| -------------------- | -----
| Bug report?          | yes
| Feature request?     | no
| BC Break report?     | no
| RFC? / Specification | no
| Library version      | 10.0

The default OTP period is 30 sec which I tried to chenge to 60 sec as per doc
`$user_secret = load_user_secret($user);`
`$OTP = TOTP::create( $user_secret, 60 );`
`$current_otp = $OTP->now();`

But at the time of verification by `$OTP->verify($posted_otp)`, It returns `false` most of the time.
Could you please help on this?

Regards
Ankit

**Comment by Spomky** [comment]
It looks like the application you are using does not support custom periods. This is the case for most of those apps, especially Google Authenticator that is commonly used.
Extracted from [the documentation](https://github.com/Spomky-Labs/otphp/blob/v10.0/doc/AppConfig.md#google-authenticator-example):

> Google only supports SHA-1 digest algorithm, 30 second period and 6 digits OTP. Other values for these parameters are ignored by the Google Authenticator application.

**Comment by ankitchauhan22** [comment]
I'm sending OTP over email not using any Mobile app. 
when I use OTP to verify within 5-10 sec, the very first attempt goes false while in second attempt after resending OTP, it verified successfully.

**Comment by Spomky** [comment]
TOTP and HOTP **are not designed** for that purpose.
The OTP should be generated randomly, stored by your server and sent by e-mail.
It should be removed once used or after a defined period of time (usually 5 to 10 minutes for this type of transmission mean).

**Comment by ankitchauhan22** [comment]
Yeah, OTP is generated randomly and not storing in file or DB. OTP is verified against the real timestamp. My question is, why 2nd OTP verification doesn't fail until we fill wrong OTP or time [60 sec] expired. The same should be happen with First OTP.

There is no change in process of generating OTP. I have only chnage the period to 60.

Regards
Ankit

**Comment by ankitchauhan22** [comment]
I fixed it
Thank you

**Comment by sirish-amatya** [comment]
@ankitchauhan22 Keen to know how you fixed it. I think i'm facing the same issue. It happens intermittently
