### ISSUE TITLE
Make setSecret() public

### ISSUE THREAD

**Issue by alecpl** [Spomky-Labs/otphp#154]
I'm migrating from version 4, and I'm wondering why setSecret() method is private. Is it a bug or there's a good reason for that?

**Comment by Spomky** [comment]
Hi,

Actually it is private because I haven't seen any reason for changing this value after the creation of the OTP object.

**Comment by alecpl** [comment]
At least setParameter('secret', $secret) works. Some old code that I deal with indeed has a few setSecret() calls, so it would be nice to allow that.

**Comment by Spomky** [comment]
Correct. No objection on that.
I will change the visibility.

**Comment by Spomky** [comment]
Done in `v10.0.3`
