### ISSUE TITLE
Invalid links in the Readme file

### ISSUE THREAD

**Issue by myramnath** [Spomky-Labs/otphp#159]
The external links to the algorithm in the description is invalid

`A php library for generating one-time passwords according to [RFC 4226](http://tools.ietf.org/html/rfc4226) (HOTP Algorithm) and [RFC 6238](http://tools.ietf.org/html/rfc6238) (TOTP Algorithm)`

**Comment by Spomky** [comment]
Hi,

I can see those URLs are redirected, but still valid.
Can you elaborate more on this?

Regards.
