### ISSUE TITLE
Dependency issue with thecodingmachine/safe

### ISSUE THREAD

**Issue by kevinpapst** [Spomky-Labs/otphp#163]
### Description

Hi!

Today I was doing a composer update on my project and suddenly `thecodingmachine/safe` popped up as download.
You are likely aware that your package is a dependecy of `scheb/2fa-totp`. And I'd say that almost every application out there using Symfony with 2FA support uses the scheb library, and therefor has your library as dependency.

When I look at your codebase where these functions are used: https://github.com/Spomky-Labs/otphp/search?q=Safe I wonder if it is really necessary that each and every app out there needs to load that code on each and every request.

I think your package as standalone version is great and does a fantastic job!

My feature request is to remove `thecodingmachine/safe` from your dependency tree. There are only two locations where the safe library is used and I hope that it is fairly easy to wrap these tiny function calls in `if false` checks instead of a `try catch` block. I know everyone is obsessed for the best code quality ... and that is great(!) but does that "safe php" approach really justify for an entire new package in the dependency tree of who knows how many apps out there?

The only other solution I see is forking your repo, just to get rid of the dependency - because we are still in the PHP world where each and every request costs resources that should be used wisely.

Let me end with a thank you for all your efforts here!

I am happy to help with a PR if you agree: https://github.com/Spomky-Labs/otphp/compare/v11.0...kevinpapst:remove-safe

**Comment by Spomky** [comment]
Correct. Done in `11.0.2`: Safe and Beberlei/Assert removed

**Comment by kevinpapst** [comment]
Wow, that were much more necessary changes than I anticipated. 

Thank you so much, not only for considering but also for applying the changes so fast!

That was a successful change:
```bash
Package operations: 0 installs, 1 update, 2 removals
  - Downloading spomky-labs/otphp (v11.0.2)
  - Removing thecodingmachine/safe (v2.4.0)
  - Removing beberlei/assert (v3.3.2)
  - Upgrading spomky-labs/otphp (v11.0.1 => v11.0.2): Extracting archive
Generating optimized autoload files
```
❤️

**Comment by Spomky** [comment]
Perfect. To be honest, in September I had a discussion with Nicolas Grekas from SensioLabs at the ApiPlatform conference and he opened my eyes on these dependencies. I planned to remove all of them and you arrived just few days after that (like all the planets aligned). I keep the last PIE constant time base32 encoder for the moment, but I will go rid of it in a near future.

**Comment by kevinpapst** [comment]
Ha, what a coincidence. 

I think dependency managers made it far too easy to include new stuff, which then itself includes other libraries. 
As library maintainer it is even more important to take care of own dependencies and that's why I'd really call that release a big success, potentially removing two packages from hundreds of apps out there. Big win 👍
