### ISSUE TITLE
`OTPInterface::create(null|string $secret = null)` is prone to misuse

### ISSUE THREAD

**Issue by Slamdunk** [Spomky-Labs/otphp#165]
### Description

`OTPInterface::create(null|string $secret = null)` API is fundamentally flawed: what happens if the user intention is to create an OTP from a *known* secret, but the variable passed is **unintentionally** `null`?

Factory methods should be splitted by intentions.

### Example

The following solutions are for `TOTP`, but can and should be applied to `HOTP` as well:

```php
interface TOTPInterface extends OTPInterface
{
    /**
     * @param non-empty-string $secret
     */
    public static function createFromSecret(
        string $secret,
        int $period = 30,
        string $digest = 'sha1',
        int $digits = 6
    ): self;

    public static function generate(
        int $period = 30,
        string $digest = 'sha1',
        int $digits = 6
    ): self;
}
```

**Comment by Spomky** [comment]
Hi,

I fully agree with you. As you say, named constructors prevent errors like the one you mentioned.

**Comment by Slamdunk** [comment]
A user-friendly API change could be:

1. Add the 2 new methods in `v11.1`
2. Deprecate `::create` in `v11.1`
3. Drop `::create` in `v12`

**Comment by Spomky** [comment]
Looks like the best approach.
As TOTP and HOTP classes are marked final, these named constructor can be added in the next minor version.
