### ISSUE TITLE
invalid OTP URI

### ISSUE THREAD

**Issue by vespino** [Spomky-Labs/otphp#179]
### Version(s) affected

11.1.0

### Description

I'm getting an error saying the OTP provision URI is unvalid using the following URI:

otpauth://totp/DoeMaatje:name@domain.ext?issuer=Name

Scanning the code with Google Authenticator does work however.

### How to reproduce

Create a QR code using the data shown above.

**Comment by Spomky** [comment]
Hi,

Indeed, `otpauth://totp/DoeMaatje:Wesley@doemaatje.nl?issuer=DoeMaatje` is not a valid URI. The `secret` parameter is missing.
Please refer to https://github.com/google/google-authenticator/wiki/Key-Uri-Format#secret

**Comment by vespino** [comment]
And I add this how?

`$otp->setSecret(<secret>);`

??

**Comment by Spomky** [comment]
How this URI is generated?
Normally, when you create a new object, the secret is randomly created (unless you explicitly specify one).
Can you share an example here?

**Comment by vespino** [comment]
```
$otp=TOTP::create();
$otp->setLabel('label');
$otp->setIssuer('issuer');

//$otp->getSecret()
//(new QRCode)->render($otp->getProvisioningUri())
```

**Comment by Spomky** [comment]
...strange behaviour...
When no secret is set, one should be generated.
I will investigate. You could use `$otp=TOTP::generate();` instead if using `v11.1.x`

**Comment by vespino** [comment]
Wait, when I echo the link, it does display the secret. Never mind, I will investigate some more on my side and come back if necessary.

**Comment by vespino** [comment]
When I remove the following the uri is valid:

`$otp->setIssuer('issuer');`

**Comment by vespino** [comment]
I think I found the problem. According to [this](https://github.com/google/google-authenticator/wiki/Key-Uri-Format) issuer must be at the end of the URI. If I check the example, it's valid. When I move issuer to the front of the URI, I get the same error I'm getting with the URI created by your script. When taking the URI creater by your script and editing it to where issuer is last (or at least after secret), the URI is valid.

Hopefully this helps?

**Comment by Spomky** [comment]
> When I move issuer to the front of the URI

I am not sure to clearly understand what you mean by this sentence.
The parameter order has no impact and I cannot see any rule for ordering the keys.
The following lines of code work perfectly and returned me a valid URI.

```php
<?php

use OTPHP\TOTP;

require_once 'vendor/autoload.php';

$otp=TOTP::create();
$otp->setLabel('label');
$otp->setIssuer('issuer');

dump($otp->getProvisioningUri());
// Returned otpauth://totp/issuer%3Alabel?issuer=issuer&secret=3ASIBUASK2SY2YGKOAG6PJDT7PBKQ74FQAODEM7HUNTDUZHA7BCEIPW2EXID5RNCFHA5RKTG6XLXIQ2GAAHULXRNJTFBP5A2R27VVJA
```

If you do not want to have the issuer in both the query parameters and the path, you can remove it with the method `setIssuerIncludedAsParameter`. Note that some applications may fail if missing from the query parameter (*We recommend using both an issuer label prefix and an issuer parameter*).

```php
<?php

use OTPHP\TOTP;

require_once 'vendor/autoload.php';

$otp=TOTP::create();
$otp->setLabel('label');
$otp->setIssuer('issuer');
$otp->setIssuerIncludedAsParameter(false);

dump($otp->getProvisioningUri());
// Returned otpauth://totp/issuer%3Alabel?secret=KSNZR5ETER7NAH6HEXD7GIG57LFDMFXX6DG7Z2HXZJFHFFF4IQOWQGZLVGODWGCLZIB6CBCEZUXME76KDSAVNSDF3BTNVNWWONT5OCI
```
