### ISSUE TITLE
PSR Clock

### ISSUE THREAD

**Issue by norkunas** [Spomky-Labs/otphp#186]
### Description

I see that in TOTP `time()` is used many times. To ease testing PSR clock could be leveraged.
Of course if there are other ways how to test the 2FA without clock mocking I'm all ears :)

**Comment by Spomky** [comment]
Hi,

Yes, that's a good idea!

**Comment by Spomky** [comment]
Hi,

You can test with the branch 11.3.x. Just let me know if you have any comments.

Regards.

**Comment by norkunas** [comment]
Nice, thank you.
