### ISSUE TITLE
generateURI doesn't work with Google authenticator

### ISSUE THREAD

**Issue by ckr** [Spomky-Labs/otphp#20]
It looks like google doesn't like digits, digest and interval in the provisioning url.

**Comment by Spomky** [comment]
I just tried to generate a TOTP including digits, digest and interval and it works fine for me.
Please, could you try this one, it is correctly loaded on Google Authenticator (v2.49) and codes generated are correct:
`otpauth://totp/Bar%3AFoo?algorithm=sha1&digits=6&issuer=Bar&period=30&secret=KRUGS4ZANFZSA3LZEBZWKY3SMV2A%3D%3D%3D%3D`
![Code](http://chart.apis.google.com/chart?cht=qr&chs=250x250&chl=otpauth%3A%2F%2Ftotp%2FBar%253AFoo%3Falgorithm%3Dsha1%26digits%3D6%26issuer%3DBar%26period%3D30%26secret%3DKRUGS4ZANFZSA3LZEBZWKY3SMV2A%253D%253D%253D%253D)

**Comment by ckr** [comment]
Still doesn't scan on google authenticator for ios

**Comment by Spomky** [comment]
OK my tests are based on Google Authenticator for Android.

If the following code is correctly loaded on your app, I will update my library.
I think I will remove parameters if algorithm=sha1, period=30 and digits=6.
`otpauth://totp/Bar%3AFoo?issuer=Bar&secret=KRUGS4ZANFZSA3LZEBZWKY3SMV2A%3D%3D%3D%3D`
![Code](http://chart.apis.google.com/chart?cht=qr&chs=250x250&chl=otpauth%3A%2F%2Ftotp%2FBar%253AFoo%3Fissuer%3DBar%26secret%3DKRUGS4ZANFZSA3LZEBZWKY3SMV2A%253D%253D%253D%253D)

**Comment by ckr** [comment]
Nope it doesn't work. If i remove the extra characters at the end it works. 
http://chart.apis.google.com/chart?cht=qr&chs=250x250&chl=otpauth%3A%2F%2Ftotp%2FBar%253AFoo%3Fissuer%3DBar%26secret%3DKRUGS4ZANFZSA3LZEBZWKY3SMV2A

![QR](http://chart.apis.google.com/chart?cht=qr&chs=250x250&chl=otpauth%3A%2F%2Ftotp%2FBar%253AFoo%3Fissuer%3DBar%26secret%3DKRUGS4ZANFZSA3LZEBZWKY3SMV2A)

**Comment by Spomky** [comment]
Thank.
I am sorry I did not notice the trailing "=" in my examples.
Please could you try again the first barcode?

I have also updated my library. It should work fine now (use the last dev-master release).
Thanks!
If it is correctly loaded, I will tag it as stable soon.

**Comment by ckr** [comment]
The second example works not the first. Thanks for the quick reply. Wouldn't not returning the algorithm=sha1, period=30 and digits=6 break other apps like FreeOTP? Maybe a send function generate google uri would be better?

**Comment by Spomky** [comment]
You are right, it could break other apps.
I added a parameter on method `getProvisioningUri`: a boolean:
- if true (default), `$totp->getProvisioningUri();` (or `$totp->getProvisioningUri(true);`) produces URIs compatible with Google Authenticator by default.
- if false, `$totp->getProvisioningUri(false);` will keep all parameters for compatibility with other apps

**Comment by rettal** [comment]
Hi, I am working with @ckr on this. We have tested and it now works fine. Thank you for the quick fix.

Will this get auto-updated on Packagist?

Thanks again!

**Comment by Spomky** [comment]
Hi,
I just release `v4.0.2`. It is already available via Packagist.

Thank for the report.
