### ISSUE TITLE
Make InternalClock not @internal?

### ISSUE THREAD

**Issue by pjordaan** [Spomky-Labs/otphp#224]
### Description

 Since spomky-labs/otphp 11.3.0: The parameter "$clock" will become mandatory in 12.0.0. Please set a valid PSR Clock implementation instead of "null"
 
 I get this error in my deprecation warnings. The fallback is using new InternalClock() now, but InternalClock is marked as ```@internal``` which also gives me a warning that I use a class marked as internal.
 
 I could implement it with my own PSR clock implementation, but maybe it's better to not mark InternalClock as an internal class?

**Comment by Spomky** [comment]
The internal class is not supposed to be used but by the library itself.
This is the expected behavior and ultimately this class will be removed in 12.0 in favor of any [PSR-20 implementation](https://packagist.org/providers/psr/clock-implementation).

**Comment by pjordaan** [comment]
Thanks for the response. So if I want to make it upgrade proof, I have to require a PSR-20 implementation and use that in the call? I'll try that then.
