### ISSUE TITLE
Verify method - interval property

### ISSUE THREAD

**Issue by waltrapa** [Spomky-Labs/otphp#26]
Hi again Spomky,

I'm not complete sure how works the verify method on TOTP scenarios. By default the interval is set to 30, but then I tried with 180, but after 120 seconds the value generated with the method verify(), returns false instead of true. I was expecting verify returns true after 180..

Interval is not related with the expire time of the OTP in seconds?

Thanks in advance

**Comment by Spomky** [comment]
Each one-time password has a lifetime that is equals to the interval you set.
For example with 180 sec as interval, today
* at 4:00 PM the OTP is 111111,
* at 4:01 PM is still 111111
* at 4:02 PM is still 111111
* at 4:03 PM is now 222222
* at 4:04 PM is still 222222
* at 4:05 PM is still 222222
* at 4:06 PM is now 111111
* and so on

If you ask to your app an OTP at 4:02 PM, the lifetime of this OTP is 180 sec, but you only have 60 sec to use it.

**Comment by waltrapa** [comment]
Ok thanks!
I updated my first question because I meant 120 seconds instead of 60 seconds sorry. Maybe you did the same mistake answering my question.
..."but you only have 60( 120 right? ) sec to use it."...
Anyway I see the point now.
