### ISSUE TITLE
Final declaration, constructors and Immutable classes

### ISSUE THREAD

**Issue by Spomky** [Spomky-Labs/otphp#38]
Opened questions:

1. I think it makes sense to declare `TOTP` and `HOTP` classes as `final`.
This declaration will be added during the next dev phase and included on `v7` of the library.

2. The creation of an OTP class is a little bit strange: no parameter is required, but the object cannot produce anything as mandatory parameters are not set (e.g. `secret`).
The constructors will be updated on `v7` and mandatory parameters required.

3. `TOTP` objects are not supposed to be modified. If a parameter is changed, then it is a new object. This classes should be immutable and setters have to be removed.
The `HOTP` object should be immutable. The only problem is that the counter has to be updated if an OTP verification succeeded.

More information about these concepts:
* http://ocramius.github.io/extremely-defensive-php/
* http://ocramius.github.io/blog/when-to-declare-classes-final/

**Comment by jkuchar** [comment]
1. by doing that you are forcing people to use encapsulation. Is it your point?
2. :+1:
3. :+1:

**Comment by Spomky** [comment]
@jkuchar yes it means that people will have to use encapsulation.
IMHO, there is no reason to extend TOTP or HOTP classes. You just have to save the provisioning URI and create your OTP object using the `Factory` to verify an OTP sent by a user.

In the following exemple, we suppose the user activated 2FA, the `User` class has a method named `getProvisioningUri()` and the `$input` argument contains digits sent by the user.
```php
use OTPHP\Factory;
use OTPHP\TOTPInterface;

function isInputValid(User $user, $input) {
    $otp = Factory::loadFromProvisioningUri($user->getProvisioningUri());
    if (!$otp instanceof TOTPInterface) {
        throw new \InvalidArgumentException('Not a TOTP');
    }
    return $otp->verify($input);
}
```

If you know cases where object Inheritance is the only way to do, please let me know and be convinced to change my mind.

**Comment by Spomky** [comment]
Done except immutable objects. See last develop commits.
Tagged as `v7.0.0`.
