### ISSUE TITLE
Do not recognize the key with issuer indicated

### ISSUE THREAD

**Issue by IgorDePaula** [Spomky-Labs/otphp#49]
If I setup the issuer, the google authenticator do not recognize the key, if I remove the issuer the google authenticator add de account.

**Comment by Spomky** [comment]
Hi,

Thank you for reporting me this issue.
Are your project up to date with the last version of this library (v7.0.4)?
A bug related to the issuer with Google Authenticator was fixed few weeks ago (see #47).

If everything is OK from your side and the issue still remain, can you tell share with me some samples (especially the issuer name) and indicate on which platform you are running Google Authenticator (Android, iOS)?

**Comment by IgorDePaula** [comment]
I'm using the dev-master version, I'm using authenticator for android,

I only copied the code from use page and add the issuer, with/without space
between words, like url and a single word (without points)

2016-07-05 13:16 GMT-03:00 Spomky <notifications@github.com>:

**Comment by IgorDePaula** [comment]
I'm updated to v7.0.4 and the error persist.

2016-07-05 14:01 GMT-03:00 principe.borodin@gmail.com <
principe.borodin@gmail.com>:

**Comment by IgorDePaula** [comment]
if Provisioning Uri is some like
otpauth://totp/alice%40bigco.com?issuer=Example&secret=JBSWY3DPEHPK3PXP

I got error key, but if Provisioning Uri some like
otpauth://totp/alice%40bigco.com?secret=JBSWY3DPEHPK3PXP&issuer=Example

I got success, but do not save the issue.

I read https://github.com/google/google-authenticator/wiki/Key-Uri-Format, but not found an answer.

**Comment by Spomky** [comment]
The examples above work fine for me.
Hereafter the QRCodes for both examples

![](http://chart.apis.google.com/chart?cht=qr&chs=250x250&chl=otpauth%3A%2F%2Ftotp%2Falice%2540bigco.com%3Fissuer%3DExample%26secret%3DJBSWY3DPEHPK3PXP)
otpauth://totp/alice%40bigco.com?issuer=Example&secret=JBSWY3DPEHPK3PXP



![](http://chart.apis.google.com/chart?cht=qr&chs=250x250&chl=otpauth%3A%2F%2Ftotp%2Falice%2540bigco.com%3Fsecret%3DJBSWY3DPEHPK3PXP%26issuer%3DExample)
otpauth://totp/alice%40bigco.com?secret=JBSWY3DPEHPK3PXP&issuer=Example

Anyway, you should not modify the provisioning Uri, but use the dedicated method.

```php
<?php
include_once 'vendor/autoload.php';

use OTPHP\TOTP;

$totp = new TOTP(
    'alice@bigco.com',
    'JBSWY3DPEHPK3PXP'
);
$totp->setIssuer('Example');

$totp->getProvisioningUri(); // Returns "otpauth://totp/Example%3Aalice%40bigco.com?issuer=Example&secret=JBSWY3DPEHPK3PXP"
```

Please note that the issuer is also set as a label prefix for compatibility with all Google Authenticator versions.

**Comment by IgorDePaula** [comment]
Yours example working, my do not.

https://gist.github.com/IgorDePaula/51c7df8ea12da75a2bc0b801d23e3552

2016-07-05 17:00 GMT-03:00 Spomky <notifications@github.com>:

**Comment by IgorDePaula** [comment]
I'm using same methods that you, and I not got.

2016-07-05 17:30 GMT-03:00 principe.borodin@gmail.com <
principe.borodin@gmail.com>:

**Comment by IgorDePaula** [comment]
I put your script here now, and do not work. Can be the QR chart api from
google?

2016-07-05 17:30 GMT-03:00 principe.borodin@gmail.com <
principe.borodin@gmail.com>:

**Comment by Spomky** [comment]
You have to encode the provisioning URI.

```php
<?php
require 'vendor/autoload.php';
use OTPHP\TOTP;
function generate_secret_key($length = 16) {
    $b32 	= "234567QWERTYUIOPASDFGHJKLZXCVBNM";
    $s 	= "";
    for ($i = 0; $i < $length; $i++)
        $s .= $b32[rand(0,31)];
    return $s;
}
$key = generate_secret_key(8);
$totp = new TOTP(
    'alice@bigco.com', $key
);
$totp->setIssuer('Example');
$encoded_provisioning_uri = urlencode($totp->getProvisioningUri());

echo "<img src='https://chart.googleapis.com/chart?chs=200x200&chld=M|0&cht=qr&chl={$encoded_provisioning_uri }'>";
```

**Comment by Spomky** [comment]
Concerning the secret generator, you should use a real random number generator instead of the rand function:

```php
use Base32\Base32;

$secret_bin = random_bytes(16);
$secret = trim(Base32::encode($secret_bin), '=');
```

If `random_bytes` is not available, you can use https://github.com/paragonie/random_compat

**Comment by IgorDePaula** [comment]
Now works fine, Thank you very much, mainly your attention and patience.

2016-07-05 17:40 GMT-03:00 Spomky <notifications@github.com>:

**Comment by Spomky** [comment]
You are welcome.
I thinl I will update the documentation and explain how to generate a valid QR Code.
Hereafter a simple example:

```php
function getProvisioningQrCode(OTPInterface $otp, $uri, $google_compatible = true)
{
    $provisioning_uri = urlencode($otp->getProvisioningUri($google_compatible));

    return str_replace('{PROVISIONING_URI}', $provisioning_uri, $uri);
}

$google_chart = getProvisioningQrCode($totp, 'https://chart.googleapis.com/chart?chs=200x200&chld=M|0&cht=qr&chl={PROVISIONING_URI}');
$goqr_me = getProvisioningQrCode($totp, 'http://api.qrserver.com/v1/create-qr-code/?color=5330FF&bgcolor=70FF7E&data={PROVISIONING_URI}&qzone=2&margin=0&size=300x300&ecc=H');

echo "<img src='{$google_chart}'>";
echo "<img src='{$goqr_me}'>";
```

**Comment by IgorDePaula** [comment]
The code on authenticator has 30seconds to change the code, but on my
device only valid in last 15second. Do you know anything?

2016-07-05 17:54 GMT-03:00 Spomky <notifications@github.com>:

**Comment by Spomky** [comment]
Google Authenticator only supports 30 sec periods.
When you get a code, it may be possible that few seconds are already over after the issuance of that code. Normally the next code periods are exactly 30 sec.

**Comment by IgorDePaula** [comment]
Ok, uI understand, again, thank you very much

2016-07-05 18:08 GMT-03:00 Spomky <notifications@github.com>:

**Comment by Spomky** [comment]
Hi,

The last dev version (`^8.0@dev`) now includes a method to easily get the correct URI to a QR Code image provided by a web service (Google Chart API or any other web service).

```php
use OTPHP\TOTP;

$otp = new TOTP(
    'alice@localhost',
    '234567QWERTYUIOPASDFGHJKLZXCVBNM'
);
$otp->setIssuer('Example');

$qr_code_img = $otp->getQrCodeUri('http://chart.apis.google.com/chart?cht=qr&chs=250x250&chl={PROVISIONING_URI}');

echo sprintf('<img src="%s">', $qr_code_img);
```

**Comment by IgorDePaula** [comment]
I very appreciate your attention for notify me, again thank you very much.

2016-07-07 4:05 GMT-03:00 Spomky <notifications@github.com>:
