### ISSUE TITLE
Get random secret

### ISSUE THREAD

**Issue by noplanman** [Spomky-Labs/otphp#57]
It would be great if there was a static method to get a randomly generated secret.

What I'm doing now is something like this:
```php
$secret = (new TOTP(''))->getSecret();
```
or simply taking the code that generates the random secret in the first place:
```php
$secret = trim(Base32::encode(random_bytes(32)), '=');
```
It just doesn't seem nice and clean to me.

Would be nice to have something along the lines of:
```php
$secret = (OTP | HOTP | TOTP)::getRandomSecret();
```

Would you welcome me PRing something? I've implemented it in my dev version and it's a small change.

**Comment by Spomky** [comment]
From my POV there is no need to have such a method.
This library is just a library that generates OTPs, not secrets.

I have implemented a method that generates 256 bits secrets (should be enough in most cases) just for developers experience but everybody is free to use its own secret generator.

**Comment by noplanman** [comment]
Ok, I understand what you mean.
I was just thinking that this library does generate a random secret when no secret is provided. ([Here](https://github.com/Spomky-Labs/otphp/blob/v8.2.0/src/ParameterTrait.php#L68))

So it would have been helpful to me if just that line would be a public static method to be used.

> I have implemented a method

You're talking about the same line I mentioned above, right?

**Comment by Spomky** [comment]
Yes I was talking about that implementation.
I decided to generate 256 bits secrets because it [seems to be an acceptable length](http://security.stackexchange.com/questions/25375/why-not-use-larger-cipher-keys/25392#25392) and developers should not care about its creation/encoding.
This internal generator uses the `random_bytes` method (PHP 7 or [paragonie/random_compat](https://github.com/paragonie/random_compat) library) which seems to be acceptable as well.

What is exactly the use case?
Why do you need to such a public method?

**Comment by noplanman** [comment]
What I have now:
```php
// Get the secret from settings or set a new one.
$secret = get_setting( 'secret' ) ?: ( new TOTP( '' ) )->getSecret();

// Get the TOTP object with the secret.
$otp = new TOTP( $user->user_login, $secret );
```

Later in the code, I need to know the "old" `$secret` from above, as the logic for a successfully loaded secret from the settings is different.

It would just be nicer to have a specific method instead of `( new TOTP( '' ) )->getSecret()`, that's all.

Or do you have any idea how I could improve this?

**Comment by noplanman** [comment]
Ok, I've changed it to this now which still works the same and doesn't need the temporary TOTP object:
```php
$otp = new TOTP(
	$user->user_login,
	get_setting( 'secret' )
);
$secret = $otp->getSecret();
```

I realised that I had needed it at some point but have found an alternative.

Thanks 👍

**Comment by Spomky** [comment]
It will work fine if `get_setting( 'secret' )` returns null (then a random secret will be created) or a Base32 encoded secret.
I recommend you to read the [wiki page I wrote about that topic](https://github.com/Spomky-Labs/otphp/wiki/What-should-I-store-in-my-server-database).

Normally you should not need the `getSecret` method. Just store the provisioning Uri and use it to create an OTP object.

**Comment by noplanman** [comment]
Have read the wiki entry, thanks for the link!

The way I'm using it now, I also show the secret to the user to allow custom entries to OTP generators. So I need the `getSecret()` at some point, even if I save the provisioning URI and then load it through the Factory.

I see what you mean though, for when parameters change, making the previous OTP configuration invalid.

> It will work fine if get_setting( 'secret' ) returns null

Right, that's what I've been making use of too.

I just feel like a bit of an idiot now, writing this issue and now realising that I don't totally remember why I needed it in the first place 😕 Everything works perfectly fine with the above code, letting `null` do the work for me.

**Comment by Spomky** [comment]
> The way I'm using it now, I also show the secret to the user to allow custom entries to OTP generators.

You are right it is sometime useful to get the secret, especially with [dedicated devices](http://www.otptoken.ro/site_en/index.php/otp-tokens/otp-token-c100).
