### ISSUE TITLE
Improvement to "How to use" documentation

### ISSUE THREAD

**Issue by arveskjorestad** [Spomky-Labs/otphp#64]
First of all: Thank you for an excellent library! 

I was pretty new to two factor authentication when I started implementing it and used this library, and I misunderstood the documentation in a way I reckon could apply to other "noobs" as well: 

In the Use.md, chapter "My first OTPs" there is an example code regarding TOTP. If you read this with limited knowledge of how TOTP is implemented, it is easy to assume that the code (123456) will *always* be valid for 30 seconds. The example states "At least 30 seconds later", while the truth is that in this example, verify() could return false after just a couple of seconds, if the code was generated at the very end of the current period.  To be able to guarantee "At least 30 seconds later" (which is what you'd normally always want when using this in a real life system), you have to set the $window argument of validate() to 1.  

I struggled quite some time understanding this, and could not figure out why my codes some times worked and some times failed long before 30 seconds. It was not until I read the docs and source code in detail I figured this out. 

So the documentation/example should maybe be updated to explain this more precise, hopefully saving others from the same frustration I encountered :)

**Comment by Spomky** [comment]
You are right the documentation is not really clear for developers and users that are not familiar with the OTPs.
Providing example is a good practice, but comments for those provided in the documentation are unclear.

I created (a new branch](https://github.com/Spomky-Labs/otphp/tree/Documentation). This branch is dedicated to documentation modifications. There is no commit at the moment. I will update it next week. Anybody is free to contribute.

**Comment by Spomky** [comment]
Hi,

v9.0 will be release by the end of June.
This issue will be taken into account. See #72 for more information or if you have comments/suggestions.

Regards.

**Comment by Spomky** [comment]
Done. See #72 and the Q&A section.

Feel free to contact me again if it is still unclear.

Thanks you.
