### ISSUE TITLE
Expire the otp once it's verified

### ISSUE THREAD

**Issue by ishtiyaq** [Spomky-Labs/otphp#66]
We should get the option to expire the totp once it's successfully verified even if the otp expire time remain.

My problem is that I am setting 5 min otp expire time because it takes time to deliver via sms, but once it's verified within a minute if I send another otp it remain same (last otp expire time is not over yet). How to resolve this problem.

**Comment by Spomky** [comment]
Hi,

I am not sure you really need this library for codes sent by email. Just generate a random one and the expiration time. You can store those data in your datadabase and check on client request. If used or expired then delete the entries.
