### ISSUE TITLE
Verify doesn't  work correctly

### ISSUE THREAD

**Issue by oatto** [Spomky-Labs/otphp#68]
I've tested some code:
```php
    public function getOtp($number)
    {
        $totp = $this->getTotp();
        $otp = $totp->now();
        sleep(5);
        return $totp->verify($otp);
    }

    protected function getTotp()
    {
        return new TOTP(null, null, 10);
    }
```

Sometimes it returns false. However, I look at this function

```php
    private function timecode($timestamp)
    {
        return (int) ((((int) $timestamp * 1000) / ($this->getPeriod() * 1000)));
    }
```

For example, I assume that period is 60 and timestamp is 118, the time code would be 1.
When timestamp is 120, time code would be changed to 2, which may makes verify function return false.

**Comment by Spomky** [comment]
Hi,

Thank you for the issue report.
I am not sure it is a bug from the library. I think that sometime it returns false because the result of the timecode function may have been rounded.

Could you try your tests using a window parameter i.e. `$totp->verify($otp, null, 1)`?

**Comment by Spomky** [comment]
In fact I think you misunderstood how period works.

In your example the OTP are valid for 10 sec. but if you get it 2 sec before it expires then 5 seconds later the test will fail.
Example: the timestamp is 123456789. The timecode is 12345678. If you wait 5 seconds the timestamp is 123456794 but the timecode is 12345679. The otp is not verified.

An OTP is always valid for the given period of time. But when you get it, it may be valid only for few seconds.

**Comment by oatto** [comment]
What's the point of a few second life for otp password in real world use ? Could you give me an example ?

**Comment by Spomky** [comment]
None and the UX . That is why [a window parameter](https://github.com/Spomky-Labs/otphp/blob/master/doc/Use.md#the-window-parameter) exists.

**Comment by oatto** [comment]
That means if I really want OTP life for 60 seconds, so I have to set period to 30 and window = 1. Am I right ?
