### ISSUE TITLE
The Google Graph API URI is a bad idea.

### ISSUE THREAD

**Issue by francislavoie** [Spomky-Labs/otphp#70]
It's not a good idea to recommend that users use the Google Graph API to generate QR codes - the OTP secret should be protected, but when putting the full secret in a request URI, it gets leaked. It's just as bad as doing something like `?user=bob&password=password123`. I really think you should remove that feature from this library. It promotes insecure usage.

The better alternative would be to use a JS library to render the QR code locally, or provide some PHP library to generate the image data as a `base64` string to be rendered in the HTML.

Thanks for the lib!

**Comment by Spomky** [comment]
The use of Google Graph is not mandatory. It is just an easy way to configure applications.
Moreover the call is over HTTPS (`https://chart.googleapis.com`) so the possible for a QRCode to be leaked should be limited.

The library allows you to define your own QRCode generator. This generator can be hosted by your own servers.
If you prefer, you can just send the provisioning Uri to your client that will render the QRCode for you (e.g. using https://davidshimjs.github.io/qrcodejs/)

**Comment by francislavoie** [comment]
Well I think that at least, the docs should be updated to mention that it's useful for development but poses a risk in production. An outside server/network shouldn't be trusted with the secrets for your application.

**Comment by Spomky** [comment]
Hi,

`v9.0` will be release by the end of June.
This issue will be taken into account. See #72 for more information or if you have comments/suggestions.

Regards.

**Comment by Spomky** [comment]
Done. See #72.

Thank you.
