### ISSUE TITLE
Release process doc should have an exception for security fixes

### ISSUE THREAD

**Issue by MisterGlass** [Spomky-Labs/otphp#75]
Thanks for making this library!

I was looking over the docs and the release process seems great, but you should add an exception to break the schedule/back compatibility rules as needed for security fixes.

**Comment by Spomky** [comment]
Hi @MisterGlass,

I am not sure to clearly understand what is expected here as there is no security fix between the current stable release and the next one.
Is there any example I could follow to perform a better DX?

**Comment by MisterGlass** [comment]
Hi @Spomky! thanks for the quick replay.

The idea is to add an exception to the rules to allow an unexpected security fix. If, say, a vulnerability was reported tomorrow, an emergency fix might be warranted. Under the current release rules, a minor fix might have to wait a month for a point release, and a non back compatible fix might need to wait a full year. That is clearly not a desirable timeline for a security fix.

Symfony recently made a non-BC change like this, you can read about it in [this blog post](https://symfony.com/blog/fixing-the-trusted-proxies-configuration-for-symfony-3-3).

I'm sure if a major issue arose the maintainers would choose security over keeping to the proscribed release schedule, but the documentation should probably be changed to reflect that possibility.

**Comment by Spomky** [comment]
Thank you for the explaination.
Can you please review the #76?
