### ISSUE TITLE
Add info to upgrade manual

### ISSUE THREAD

**Issue by grevus** [Spomky-Labs/otphp#88]
| Q                    | A
| -------------------- | -----
| Documentation | yes
| Library version      | 9+

Please, add information that you changed library for Base32 encoding to this file:
>  otphp/UPGRADE_v8-v9.md

```
-        $encoded_secret =  Base32\Base32::encode($secret);
+        $encoded_secret =  ParagonIE\ConstantTime\Base32::encodeUpper($secret);
```

**Comment by Spomky** [comment]
Good catch.

As the version `8.3` is concerned by this change, I modified the [README file](https://github.com/Spomky-Labs/otphp#base-32-encoder) instead of the `otphp/UPGRADE_v8-v9.md` one.

Thanks

**Comment by grevus** [comment]
Thanks
