### ISSUE TITLE
Base32 encode vs encodeUpper

### ISSUE THREAD

**Issue by watermark** [Spomky-Labs/otphp#89]
Using version 8.3.2, the base32 class was changed.  When a string encoded with the normal "Base32::encode" function is set as the secret, the TOTP->verify function fails because it tries to decode the string with "Base32::decodeUpper".  If the original string is encoded with Base::encodeUpper then the verify works fine.

To avoid the regression, I think it would be most appropriate to modify the ParameterTrait->setSecret function to pass the secret through a php "strtoupper" call.

**Comment by Spomky** [comment]
Lets discuss about it in the PR.
